### ISSUE TITLE
ImageNotFoundException

### ISSUE THREAD

**Issue by n3t5pLi7** [HjOtal-1/Glimmer-and-Gloom#3]
Getting a confidence level of .888 but its saying the following error.  its not even starting to solve for some reason

C:\Users\x\Downloads\Glimmer-and-Gloom-master\Glimmer-and-Gloom-master>autorun.py
Starting the game, we'll play 19 rounds.
Beginning round #1...
Traceback (most recent call last):
  File "C:\Users\x\Downloads\Glimmer-and-Gloom-master\Glimmer-and-Gloom-master\autorun.py", line 17, in <module>
    solve_board()
  File "C:\Users\x\Downloads\Glimmer-and-Gloom-master\Glimmer-and-Gloom-master\board_solver.py", line 242, in solve_board
    gameBoard = GameBoard()
                ^^^^^^^^^^^
  File "C:\Users\x\Downloads\Glimmer-and-Gloom-master\Glimmer-and-Gloom-master\board_solver.py", line 49, in __init__
    self.find_all()
  File "C:\Users\x\Downloads\Glimmer-and-Gloom-master\Glimmer-and-Gloom-master\board_solver.py", line 69, in find_all
    for box in pyautogui.locateAllOnScreen(
  File "C:\Users\x\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyscreeze\__init__.py", line 257, in _locateAll_opencv
    raise ImageNotFoundException('Could not locate the image (highest confidence = %.3f)' % result.max())
pyscreeze.ImageNotFoundException: Could not locate the image (highest confidence = 0.888)

any suggestions?

**Comment by Angrones** [comment]
Super late, sorry.

"0.888" isn't acceptable for the confidence level, it has to be between 0.0 and 1.0. :'D
